name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain:
          - "1.81" # minimum for this crate
          - "stable"
          - "nightly"
    steps:
      - uses: actions/checkout@v4 # not pinning to commit hash since this is a GitHub action, which we trust
      - uses: actions-rust-lang/setup-rust-toolchain@9d7e65c320fdb52dcd45ffaa68deb6c02c8754d9 # v1.12.0
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rustfmt, clippy
      - name: Check
        run: cargo check
      - name: Architecture check
        run: cargo run arch-check
      - name: Architecture check (Optimized)
        run: cargo run --features=optimize_crc32_auto arch-check
      - if: ${{ matrix.rust-toolchain != 'nightly' }}
        name: Format
        run: cargo fmt -- --check
      - if: ${{ matrix.rust-toolchain != 'nightly' }}
        name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test
      - name: Test (Optimized)
        run: cargo test --features=optimize_crc32_auto